#theme: jekyll-theme-0fp0-monetize

author :
  name : Fajar Purnama
  email : fajar.purnama@yahoo.com
  github : 0fajarpurnama0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

#title: {{ page.title }}
#tagline: {{ page.description }}
#description: {{ page.description }}
#image: {{ page.featuredimage }}
logo: /assets/images/icon/Logo-0FP0-square.png

sass:
    sass_dir: _sass
