# --- Site Settings ---
title: Fajar Purnama Website
description: "Fajar Purnama website built with Jekyll."
url: "https://0fajarpurnama0.github.io"
lang: en
timezone: Asia/Makassar  # Set to your local time (WITA)

# --- Author Settings ---
author:
  name: Fajar Purnama
  email: fajar.purnama@yahoo.com
  github: 0fajarpurnama0
  twitter: 0FajarPurnama0

# --- Assets ---
logo: /assets/images/icon/Logo-0FP0-square.png
# Default social share image (used if a post has no specific image)
image: /assets/images/icon/Logo-0FP0-square.png

# --- Plugins ---
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# --- Webmaster Verifications (Used by jekyll-seo-tag) ---
webmaster_verifications:
  google: FWcVBnd6PEqZXqusku_mWvp_wiqeV1wCao_PkYTmJ1g
  bing: 54D8641EDD0279CDEEDFCA58B63A3719
  yandex: e046aa5f90432f45
  facebook: 1hnosshf5gzygrcvsawm2ehnuu9b22

# --- Social Profiles (Used by jekyll-seo-tag for JSON-LD) ---
# Note: I kept your list exactly as is.
social:
  name: Fajar Purnama
  links:
    - https://github.com/0fajarpurnama0
    - https://www.torum.com/u/0fajarpurnama0?referral_code=0fajarpurnama0
    - https://www.minds.com/0fajarpurnama0?referrer=0fajarpurnama0
    - https://memo.cash/profile/13aFutkrWkURvrJ8MWqXeHUYZkxV1jmoy4
    - https://www.floyx.com/profile/0fajarpurnama0/posts?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjBmYWphcnB1cm5hbWEwIn0.qOEBl8cXWaC-jeGlbBCUdaa1LaCyqpEGWZuSCXjrG6A
    - https://noise.cash/u/FajarPurnama
    - https://www.uhive.com/z/1ST4KB1
    - https://revain.org/authors/10eeba1c-7428-4d8a-b1bf-a9cadf18b7b7?referralToken=6bd10c5f-b755-4544-861d-52fdb4ecd260
    - https://hive.blog/@fajar.purnama?ref=fajar.purnama
    - https://steemit.com/@fajar.purnama?r=fajar.purnama
    - https://blurt.blog/@fajar.purnama?referral=fajar.purnama
    - https://markethive.com/0fajarpurnama0
    - https://odysee.com/$/invite/@0fajarpurnama0:e
    - https://opensea.io/0fajarpurnama0
    - https://rarible.com/0fajarpurnama0
    - https://exchange.yetiswap.app/#/profile/0xCf354A0012160bC5dAe441C49f0B2d7E4A4fFC96
    - https://www.bakeryswap.org/#/usercenter/0xD9c6F048c08bCb24190C0FDE5BbC622f51F83469
    - https://www.publish0x.com/0fajarpurnama0?a=4oeEw0Yb0B&tid=github
    - https://www.loop.markets/user/36801
    - https://www.bitchute.com/channel/0fajarpurnama0
    - https://dlive.tv/fajarpurnama
    - https://d.tube/#!/c/fajar.purnama
    - https://twitter.com/0FajarPurnama0
    - https://www.facebook.com/fajar.purnama.543
    - https://instagram.com/0fajarpurnama0
    - https://www.linkedin.com/in/fajar-purnama-45583780
    - https://discord.gg/aDRAu7Q
    - https://www.reddit.com/user/0fajarpurnama0
    - https://vk.com/0fajarpurnama0
    - https://id.pinterest.com/fajarpurnamaabc
    - https://social.eaglerockglobal.org/0fajarpurnama0
    - https://www.wowapp.com/w/fajar.purnama
    - https://www.youtube.com/c/PurnamaABC
    - https://www.twitch.tv/0fajarpurnama0
    - https://medium.com/@0fajarpurnama0
    - http://www.dreamjournal.net/journal/default/username/0fajarpurnama0
    - https://www.flickr.com/photos/0fajarpurnama0
    - https://www.chess.com/blog/0fajarpurnama0
    - https://lichess.org/@/fajarpurnama
    - http://0darkking0.blogspot.com
    - https://0fajarpurnama0.weebly.com
    - https://0fajarpurnama0.wixsite.com/0fajarpurnama0
    - https://refer.codes/0fajarpurnama0/

# --- Build Settings ---
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

# Collections
collections:
  others:
    output: true
    permalink: /:path/

exclude:
  - .git
  - .gitmodules
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
  - "**/node_modules"
  - "**/.git"
  - "**/.gitmodules"
  - "**/.gitignore"